Modules = [
    "github.com/hexya-addons/sale"
]
LogStdout = true
#LogFile = ""
LogLevel = "info"
#Debug = true
Demo = true
#DataDir = ""

[DB]
#Driver = "postgres"
#Host = "/var/run/postgresql"
#Port = 5432
#User = ""
#Password = ""
#Name = "hexya"
#SSLMode = false
#SSLCert = ""
#SSLKey = ""
#SSLCA = ""

[Server]
Languages = ["fr"]
#Interface = ""
#Port = 8080
#Domain = ""
#Certificate = ""
#PrivateKey = ""
