Modules = [
    "github.com/hexya-erp/hexya-addons/sale"
]
LogStdout = true
#LogFile = ""
LogLevel = "debug"
#Debug = false
Demo = true
#DataDir = ""

[DB]
#Driver = "postgres"
#Host = "/var/run/postgresql"
#Port = 5432
#User = ""
#Password = ""
#Name = "hexya"
#SSLMode = false
#SSLCert = ""
#SSLKey = ""
#SSLCA = ""

[Server]
Languages = ["fr"]
#Interface = ""
#Port = 8080
#Domain = ""
Certificate = "/home/npiganeau/Progs/cert.pem"
PrivateKey = "/home/npiganeau/Progs/key.pem"
