Modules = [
    "github.com/hexya-erp/hexya-addons/sale"
]
LogStdout = true
#LogFile = ""
#LogLevel = "info"
#Debug = false
#DataDir = ""

[DB]
#Driver = "postgres"
#Host = "/var/run/postgresql"
#Port = 5432
#User = ""
#Password = ""
#Name = "hexya"

[Server]
Languages = ["fr"]
#Interface = ""
#Port = 8080
